name: Publish to NPM

on:
  release:
    types: [ published ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write  # Required for OIDC to publish to NPM
  contents: read

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Detect coding standard violations
        run: yarn lint

  publish:
    needs: check
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      # We can't install anything globally with the set permissions for the default version of npm that setup-node comes with.
      # So, we need to install it in the user space where we do have file permissions.
      - name: Set npm prefix to user space
        run: npm config set prefix "${HOME}/.npm-global"
      - name: Update PATH to use NPM from user space
        run: echo "${HOME}/.npm-global/bin" >> $GITHUB_PATH
      # Ensure npm 11.5.1 or later is installed - this is needed for OIDC support
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm publish --verbose --access public
